CREATE TABLE PATIENTS (
  ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
  LEGALCODE VARCHAR2(20),
  NAME      VARCHAR2(255),
  SURNAME   VARCHAR2(255),
  ADDRESS   VARCHAR2(255),
  PHONE     VARCHAR2(30),
  EMAIL     VARCHAR2(50),
  BIRTHDATE DATETIME,
  GENDER    VARCHAR2(6),
  SMOKING   BOOLEAN DEFAULT FALSE,
  PREGNANCY BOOLEAN DEFAULT FALSE,
  LACTATION BOOLEAN DEFAULT FALSE,
  PASSWORD  VARCHAR2(255),
  ROLE      VARCHAR2(45)
);

CREATE TABLE DIAGNOSISCLASSIFIERS (
  CODE VARCHAR2(50) PRIMARY KEY,
  NAME VARCHAR2(100)
);

CREATE TABLE MEASUREMENTCLASSIFIERS (
  CODE VARCHAR2(50) PRIMARY KEY,
  NAME VARCHAR2(100),
  UNIT VARCHAR2(30)
);

CREATE TABLE MEDICATIONCLASSIFIERS (
  CODE VARCHAR2(50) PRIMARY KEY,
  NAME VARCHAR2(100),
  UNIT VARCHAR2(30)
);

CREATE TABLE PROCEDURECLASSIFIERS (
  CODE VARCHAR2(50) PRIMARY KEY,
  NAME VARCHAR2(100)
);

CREATE TABLE VACCINECLASSIFIERS (
  CODE VARCHAR2(50) PRIMARY KEY,
  NAME VARCHAR2(100),
  UNIT VARCHAR2(30)
);

CREATE TABLE PATIENTDIAGNOSES (
  ID                       BIGINT AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID               BIGINT,
  DIAGNOSISCLASSIFIER_CODE VARCHAR(50),
  STARTDATE                DATETIME,
  ENDDATE                  DATETIME,
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (DIAGNOSISCLASSIFIER_CODE) REFERENCES DIAGNOSISCLASSIFIERS (CODE)
);

CREATE TABLE PATIENTMEASUREMENTS (
  ID                         BIGINT AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID                 BIGINT,
  MEASUREMENTCLASSIFIER_CODE VARCHAR(50),
  VALUE                      DOUBLE,
  DATE                       DATETIME,
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (MEASUREMENTCLASSIFIER_CODE) REFERENCES MEASUREMENTCLASSIFIERS (CODE)
);

CREATE TABLE PATIENTMEDICATIONS (
  ID                        BIGINT AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID                BIGINT,
  MEDICATIONCLASSIFIER_CODE VARCHAR(50),
  STARTDATE                 DATETIME,
  ENDDATE                   DATETIME,
  STRENGTH                  VARCHAR2(50),
  DOSAGE                    VARCHAR2(50),
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (MEDICATIONCLASSIFIER_CODE) REFERENCES MEDICATIONCLASSIFIERS (CODE)
);

CREATE TABLE PATIENTPROCEDURES (
  ID                       BIGINT AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID               BIGINT,
  PROCEDURECLASSIFIER_CODE VARCHAR(50),
  DATE                     DATETIME,
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (PROCEDURECLASSIFIER_CODE) REFERENCES PROCEDURECLASSIFIERS (CODE)
);

CREATE TABLE PATIENTVACCINATIONS (
  ID                     BIGINT AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID             BIGINT,
  VACCINECLASSIFIER_CODE VARCHAR(50),
  STARTDATE              DATETIME,
  ENDDATE                DATETIME,
  STRENGTH               VARCHAR2(50),
  DOSE                   VARCHAR2(50),
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (VACCINECLASSIFIER_CODE) REFERENCES VACCINECLASSIFIERS (CODE)
);

CREATE TABLE PATIENTDRUGSTOAVOID (
  PATIENT_ID                BIGINT,
  MEDICATIONCLASSIFIER_CODE VARCHAR(50),
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (MEDICATIONCLASSIFIER_CODE) REFERENCES MEDICATIONCLASSIFIERS (CODE),
  PRIMARY KEY (PATIENT_ID, MEDICATIONCLASSIFIER_CODE)
);

CREATE TABLE PATIENTACTIONS (
  ID         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATE       DATETIME,
  PATIENT_ID BIGINT,
  ACTIONTYPE VARCHAR(30),
  DATA       TEXT
);

CREATE TABLE HEALTHSTATEMENTLIFESTYLE (
  ID                BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ALCOHOL           BOOLEAN DEFAULT FALSE,
  ALCOHOLUNITS      VARCHAR(255),
  SMOKING           BOOLEAN DEFAULT FALSE,
  CIGARETTESPERDAY  VARCHAR(255),
  SMOKINGYEARS      VARCHAR(255),
  WHENQUITSMOKING   VARCHAR(255),
  DRUGS             BOOLEAN DEFAULT FALSE,
  DRUGSHOWOFTEN     VARCHAR(255),
  MEDICATIONSTHATAFFECTCOORDINATION BOOLEAN DEFAULT FALSE,
  SLEEPHABITS       VARCHAR(255)
);

CREATE TABLE HEALTHSTATEMENTMEDICALDEVICES (
  ID                      BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  GLASSES                 BOOLEAN DEFAULT FALSE,
  CONTACTLENSES           BOOLEAN DEFAULT FALSE,
  HEARINGAID              BOOLEAN DEFAULT FALSE,
  LEGPROSTHESIS           BOOLEAN DEFAULT FALSE,
  ARMPROSTHESIS           BOOLEAN DEFAULT FALSE,
  MOBILITYSUPPORTDEVICE   BOOLEAN DEFAULT FALSE,
  SURGERY                 BOOLEAN DEFAULT FALSE,
  OTHER                   VARCHAR(255)
);

CREATE TABLE HEALTHSTATEMENTCARDIOVASCULARCONDITION (
  ID                BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CHESTPAIN         BOOLEAN DEFAULT FALSE,
  HIGHBLOODPRESSURE BOOLEAN DEFAULT FALSE,
  HEARTATTACK       BOOLEAN DEFAULT FALSE,
  ARRYTHMIA         BOOLEAN DEFAULT FALSE,
  ANGIOPLASTY       BOOLEAN DEFAULT FALSE,
  PACEMAKER         BOOLEAN DEFAULT FALSE,
  HEARTSURGERY      BOOLEAN DEFAULT FALSE,
  OTHER             VARCHAR(255)

);

CREATE TABLE HEALTHSTATEMENTALLERGIES (
  ID             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DRUGS          VARCHAR(255),
  FOOD           VARCHAR(255),
  DOMESTICPETS   VARCHAR(255),
  POLLEN         VARCHAR(255),
  OTHER          VARCHAR(255)
);

CREATE TABLE HEALTHSTATEMENTWORKINGENVIRONMENT (
  ID                      BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RESTRICTIONS            BOOLEAN DEFAULT FALSE,
  RESTRICTIONSDESCRIPTION VARCHAR(255),
  HEALTHPROBLEMS          BOOLEAN DEFAULT FALSE
);

CREATE TABLE HEALTHSTATEMENT (
  ID                          BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID                  BIGINT,
  LIFESTYLE_ID                BIGINT,
  MEDICALDEVICES_ID           BIGINT,
  CARDIOVASCULARCONDITION_ID  BIGINT,
  WORKINGENVIRONMENT_ID       BIGINT,
  ALLERGIES_ID                BIGINT,
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (LIFESTYLE_ID) REFERENCES HEALTHSTATEMENTLIFESTYLE (ID),
  FOREIGN KEY (MEDICALDEVICES_ID) REFERENCES HEALTHSTATEMENTMEDICALDEVICES (ID),
  FOREIGN KEY (CARDIOVASCULARCONDITION_ID) REFERENCES HEALTHSTATEMENTCARDIOVASCULARCONDITION (ID),
  FOREIGN KEY (WORKINGENVIRONMENT_ID) REFERENCES HEALTHSTATEMENTWORKINGENVIRONMENT (ID),
  FOREIGN KEY (ALLERGIES_ID) REFERENCES HEALTHSTATEMENTALLERGIES (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE NOTES (
  ID         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID BIGINT,
  NOTES      TEXT,
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID)
);

CREATE TABLE SELFHEALTHCHECK (
  ID                       BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PATIENT_ID               BIGINT,
  HEADACHE                 BOOLEAN         DEFAULT FALSE,
  PAININBONES              BOOLEAN         DEFAULT FALSE,
  PAININRESPIRATORYTRACT   BOOLEAN         DEFAULT FALSE,
  STOMACHACHETOP           BOOLEAN         DEFAULT FALSE,
  STOMACHACHEMIDDLE        BOOLEAN         DEFAULT FALSE,
  STOMACHACHEBOTTOM        BOOLEAN         DEFAULT FALSE,
  RHEUM                    BOOLEAN         DEFAULT FALSE,
  COUGH                    BOOLEAN         DEFAULT FALSE,
  PAININTHROAT             BOOLEAN         DEFAULT FALSE,
  PAININLUNGS              BOOLEAN         DEFAULT FALSE,
  RHEUMANDTHROAT           BOOLEAN         DEFAULT FALSE,
  STITCHESINHEARTZONE      BOOLEAN         DEFAULT FALSE,
  STITCHESINOTHERBODYPARTS BOOLEAN         DEFAULT FALSE,
  CARDIACRHYTHMDISORDERS   BOOLEAN         DEFAULT FALSE,
  FEVER                    BOOLEAN         DEFAULT FALSE,
  VOMITING                 BOOLEAN         DEFAULT FALSE,
  DIARRHEA                 BOOLEAN         DEFAULT FALSE,
  INJURY                   BOOLEAN         DEFAULT FALSE,
  INFLAMMATIONVISIBLE      BOOLEAN         DEFAULT FALSE,
  INFLAMMATIONNOTVISIBLE   BOOLEAN         DEFAULT FALSE,
  URINATION                BOOLEAN         DEFAULT FALSE,
  ANXIETY                  BOOLEAN         DEFAULT FALSE,

  PRIMARY KEY (ID),
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID)
)


