ALTER TABLE PATIENTMEASUREMENTS ADD IMPORTED TINYINT(1) DEFAULT 0;

ALTER TABLE MEDICATIONCLASSIFIERS DROP PRIMARY KEY, ADD PRIMARY KEY(CODE, NAME);
ALTER TABLE DIAGNOSISCLASSIFIERS DROP PRIMARY KEY, ADD PRIMARY KEY(CODE, NAME);
ALTER TABLE MEASUREMENTCLASSIFIERS DROP PRIMARY KEY, ADD PRIMARY KEY(CODE, NAME);
ALTER TABLE PROCEDURECLASSIFIERS DROP PRIMARY KEY, ADD PRIMARY KEY(CODE, NAME);
ALTER TABLE VACCINECLASSIFIERS DROP PRIMARY KEY, ADD PRIMARY KEY(CODE, NAME);

ALTER TABLE PATIENTMEDICATIONS ADD MEDICATIONCLASSIFIER_NAME VARCHAR(100);
ALTER TABLE PATIENTDIAGNOSES ADD DIAGNOSISCLASSIFIER_NAME VARCHAR(100);
ALTER TABLE PATIENTMEASUREMENTS ADD MEASUREMENTCLASSIFIER_NAME VARCHAR(100);
ALTER TABLE PATIENTPROCEDURES ADD PROCEDURECLASSIFIER_NAME VARCHAR(100);
ALTER TABLE PATIENTVACCINATIONS ADD VACCINECLASSIFIER_NAME VARCHAR(100);
ALTER TABLE PATIENTDRUGSTOAVOID ADD MEDICATIONCLASSIFIER_NAME VARCHAR(100);

