DROP TABLE HEALTHSTATEMENT;

/**
  Health statement medical devices
 */
DROP TABLE HEALTHSTATEMENTMEDICALDEVICES;
CREATE TABLE HEALTHSTATEMENTMEDICALDEVICES (
  ID                           BIGINT NOT NULL AUTO_INCREMENT,
  NONE                         BOOLEAN         DEFAULT FALSE,
  GLASSES                      BOOLEAN         DEFAULT FALSE,
  GLASSESDETAILS               VARCHAR(255),
  CONTACTLENSES                BOOLEAN         DEFAULT FALSE,
  CONTACTLENSESDETAILS         VARCHAR(255),
  HEARINGAID                   BOOLEAN         DEFAULT FALSE,
  HEARINGAIDDETAILS            VARCHAR(255),
  LEGPROSTHESIS                BOOLEAN         DEFAULT FALSE,
  LEGPROSTHESISDETAILS         VARCHAR(255),
  ARMPROSTHESIS                BOOLEAN         DEFAULT FALSE,
  ARMPROSTHESISDETAILS         VARCHAR(255),
  MOBILITYSUPPORTDEVICE        BOOLEAN         DEFAULT FALSE,
  MOBILITYSUPPORTDEVICEDETAILS VARCHAR(255),
  OTHERDEVICE                  BOOLEAN         DEFAULT FALSE,
  OTHERDEVICEDETAILS           VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement life style
 */
DROP TABLE HEALTHSTATEMENTLIFESTYLE;
CREATE TABLE HEALTHSTATEMENTLIFESTYLE (
  ID                             BIGINT NOT NULL AUTO_INCREMENT,
  ALCOHOL                        BOOLEAN         DEFAULT FALSE,
  ALCOHOLUNITS                   VARCHAR(255),
  SMOKING                        BOOLEAN         DEFAULT FALSE,
  CIGARETTESPERDAY               VARCHAR(255),
  SMOKINGYEARS                   VARCHAR(255),
  WHENQUITSMOKING                VARCHAR(255),
  DRUGS                          BOOLEAN         DEFAULT FALSE,
  DRUGSHOWOFTEN                  VARCHAR(255),
  MEDICAFFECTCOORDINATION        BOOLEAN         DEFAULT FALSE,
  MEDICAFFECTCOORDINATIONDETAILS VARCHAR(255),
  SLEEPHABITS                    VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement cardiovascular condition
 */
DROP TABLE HEALTHSTATEMENTCARDIOVASCULARCONDITION;
CREATE TABLE HEALTHSTATEMENTCARDIOVASCULARCONDITION (
  ID                       BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS              BOOLEAN         DEFAULT FALSE,
  CHESTPAIN                BOOLEAN         DEFAULT FALSE,
  CHESTPAINDETAILS         VARCHAR(255),
  HIGHBLOODPRESSURE        BOOLEAN         DEFAULT FALSE,
  HIGHBLOODPRESSUREDETAILS VARCHAR(255),
  HEARTATTACK              BOOLEAN         DEFAULT FALSE,
  HEARTATTACKDETAILS       VARCHAR(255),
  ARRYTHMIA                BOOLEAN         DEFAULT FALSE,
  ARRYTHMIADETAILS         VARCHAR(255),
  ANGIOPLASTY              BOOLEAN         DEFAULT FALSE,
  ANGIOPLASTYDETAILS       VARCHAR(255),
  PACEMAKER                BOOLEAN         DEFAULT FALSE,
  PACEMAKERDETAILS         VARCHAR(255),
  HEARTSURGERY             BOOLEAN         DEFAULT FALSE,
  HEARTSURGERYDETAILS      VARCHAR(255),
  OTHERDISEASE             BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS      VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement allergies
 */
DROP TABLE HEALTHSTATEMENTALLERGIES;
CREATE TABLE HEALTHSTATEMENTALLERGIES (
  ID                  BIGINT NOT NULL AUTO_INCREMENT,
  NONE                BOOLEAN         DEFAULT FALSE,
  DRUGS               BOOLEAN         DEFAULT FALSE,
  DRUGSDETAILS        VARCHAR(255),
  FOOD                BOOLEAN         DEFAULT FALSE,
  FOODDETAILS         VARCHAR(255),
  DOMESTICPETS        BOOLEAN         DEFAULT FALSE,
  DOMESTICPETSDETAILS VARCHAR(255),
  POLLEN              BOOLEAN         DEFAULT FALSE,
  POLLENDETAILS       VARCHAR(255),
  OTHER               BOOLEAN         DEFAULT FALSE,
  OTHERDETAILS        VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement working environments
 */

DROP TABLE HEALTHSTATEMENTWORKINGENVIRONMENT;
CREATE TABLE HEALTHSTATEMENTWORKINGENVIRONMENT (
  ID                    BIGINT NOT NULL AUTO_INCREMENT,
  RESTRICTIONS          BOOLEAN         DEFAULT FALSE,
  RESTRICTIONSDETAILS   VARCHAR(255),
  HEALTHPROBLEMS        BOOLEAN         DEFAULT FALSE,
  HEALTHPROBLEMSDETAILS VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement Blood problems
 */
CREATE TABLE HEALTHSTATEMENTBLOODPROBLEMS (
  ID                  BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS         BOOLEAN         DEFAULT FALSE,
  ANEMIA              BOOLEAN         DEFAULT FALSE,
  ANEMIADETAILS       VARCHAR(255),
  OTHERDISEASE        BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement Bones, joints and muscles
 */
CREATE TABLE HEALTHSTATEMENTBONESJOINTSMUSCLES (
  ID                     BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS            BOOLEAN         DEFAULT FALSE,
  JOINTSTIFFNESS         BOOLEAN         DEFAULT FALSE,
  JOINTSTIFFNESSDETAILS  VARCHAR(255),
  PARALYSISOFLIMB        BOOLEAN         DEFAULT FALSE,
  PARALYSISOFLIMBDETAILS VARCHAR(255),
  MISSINGLIMB            BOOLEAN         DEFAULT FALSE,
  MISSINGLIMBDETAILS     VARCHAR(255),
  TREMBLINGHANDS         BOOLEAN         DEFAULT FALSE,
  TREMBLINGHANDSDETAILS  VARCHAR(255),
  JOINTPAIN              BOOLEAN         DEFAULT FALSE,
  JOINTPAINDETAILS       VARCHAR(255),
  NECKPAIN               BOOLEAN         DEFAULT FALSE,
  NECKPAINDETAILS        VARCHAR(255),
  SHOULDERPAIN           BOOLEAN         DEFAULT FALSE,
  SHOULDERPAINDETAILS    VARCHAR(255),
  LOWERBACKPAIN          BOOLEAN         DEFAULT FALSE,
  LOWERBACKPAINDETAILS   VARCHAR(255),
  OTHERDISEASE           BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS    VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement digestive organs
 */
CREATE TABLE HEALTHSTATEMENTDIGESTIVEORGANS (
  ID                           BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS                  BOOLEAN         DEFAULT FALSE,
  LIVERDISEASE                 BOOLEAN         DEFAULT FALSE,
  LIVERDISEASEDETAILS          VARCHAR(255),
  GALLSTONES                   BOOLEAN         DEFAULT FALSE,
  GALLSTONESDETAILS            VARCHAR(255),
  GASTRICDUODENALULCERS        BOOLEAN         DEFAULT FALSE,
  GASTRICDUODENALULCERSDETAILS VARCHAR(255),
  ULCERATIVECOLITIS            BOOLEAN         DEFAULT FALSE,
  ULCERATIVECOLITISDETAILS     VARCHAR(255),
  OTHERDISEASE                 BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS          VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement ear, nose, throat
 */
CREATE TABLE HEALTHSTATEMENTEARNOSETHROAT (
  ID                            BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS                   BOOLEAN         DEFAULT FALSE,
  HEARINGLOSS                   BOOLEAN         DEFAULT FALSE,
  HEARINGLOSSDETAILS            VARCHAR(255),
  ALLERGICRHINITIS              BOOLEAN         DEFAULT FALSE,
  ALLERGICRHINITISDETAILS       VARCHAR(255),
  CHRONICSINUSITIS              BOOLEAN         DEFAULT FALSE,
  CHRONICSINUSITISDETAILS       VARCHAR(255),
  NASALOBSTRUCTION              BOOLEAN         DEFAULT FALSE,
  NASALOBSTRUCTIONDETAILS       VARCHAR(255),
  FREQUENTHHROATPROBLEMS        BOOLEAN         DEFAULT FALSE,
  FREQUENTHHROATPROBLEMSDETAILS VARCHAR(255),
  OTHERDISEASE                  BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS           VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement eyes and vision
 */
CREATE TABLE HEALTHSTATEMENTEYESANDVISION (
  ID                            BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS                   BOOLEAN         DEFAULT FALSE,
  SHORTSIGHTEDNESS              BOOLEAN         DEFAULT FALSE,
  SHORTSIGHTEDNESSDETAILS       VARCHAR(255),
  VISUALFIELDRESTRICTION        BOOLEAN         DEFAULT FALSE,
  VISUALFIELDRESTRICTIONDETAILS VARCHAR(255),
  DOUBLEVISION                  BOOLEAN         DEFAULT FALSE,
  DOUBLEVISIONDETAILS           VARCHAR(255),
  COLOURVISIONDISORDERS         BOOLEAN         DEFAULT FALSE,
  COLOURVISIONDISORDERSDETAILS  VARCHAR(255),
  OTHERDISEASE                  BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS           VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement infectious diseases
 */
CREATE TABLE HEALTHSTATEMENTINFECTIOUSDISEASES (
  ID                    BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS           BOOLEAN         DEFAULT FALSE,
  TUBERCULOSIS          BOOLEAN         DEFAULT FALSE,
  TUBERCULOSISDETAILS   VARCHAR(255),
  VIIRUSHEPATIIT        BOOLEAN         DEFAULT FALSE,
  VIIRUSHEPATIITDETAILS VARCHAR(255),
  HIVCARRIER            BOOLEAN         DEFAULT FALSE,
  HIVCARRIERDETAILS     VARCHAR(255),
  AIDS                  BOOLEAN         DEFAULT FALSE,
  AIDSDETAILS           VARCHAR(255),
  OTHERDISEASE          BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS   VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement mental health
 */
CREATE TABLE HEALTHSTATEMENTMENTALHEALTH (
  ID                        BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS               BOOLEAN         DEFAULT FALSE,
  DEPRESSION                BOOLEAN         DEFAULT FALSE,
  DEPRESSIONDETAILS         VARCHAR(255),
  SCHIZOPHRENIA             BOOLEAN         DEFAULT FALSE,
  SCHIZOPHRENIADETAILS      VARCHAR(255),
  FEAROFWORKINGALONE        BOOLEAN         DEFAULT FALSE,
  FEAROFWORKINGALONEDETAILS VARCHAR(255),
  FEAROFCLOSEDSPACES        BOOLEAN         DEFAULT FALSE,
  FEAROFCLOSEDSPACESDETAILS VARCHAR(255),
  FEAROFHEIGHTS             BOOLEAN         DEFAULT FALSE,
  FEAROFHEIGHTSDETAILS      VARCHAR(255),
  OTHERDISEASE              BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS       VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement metabolic disorders
 */
CREATE TABLE HEALTHSTATEMENTMETABOLICDISORDERS (
  ID                  BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS         BOOLEAN         DEFAULT FALSE,
  DIABETES            BOOLEAN         DEFAULT FALSE,
  DIABETESDETAILS     VARCHAR(255),
  OTHERDISEASE        BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement nervous system
 */
CREATE TABLE HEALTHSTATEMENTNERVOUSSYSTEM (
  ID                        BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS               BOOLEAN         DEFAULT FALSE,
  FAINTINGSPELLS            BOOLEAN         DEFAULT FALSE,
  FAINTINGSPELLSDETAILS     VARCHAR(255),
  CONVULSIONS               BOOLEAN         DEFAULT FALSE,
  CONVULSIONSDETAILS        VARCHAR(255),
  BALANCEDISORDERS          BOOLEAN         DEFAULT FALSE,
  BALANCEDISORDERSDETAILS   VARCHAR(255),
  CEREBRALINFARCTION        BOOLEAN         DEFAULT FALSE,
  CEREBRALINFARCTIONDETAILS VARCHAR(255),
  SEASICKNESS               BOOLEAN         DEFAULT FALSE,
  SEASICKNESSDETAILS        VARCHAR(255),
  OTHERDISEASE              BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS       VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement other chronic diseases
 */
CREATE TABLE HEALTHSTATEMENTOTHERCHRONICDISEASES (
  ID             BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS    BOOLEAN         DEFAULT FALSE,
  DISEASE        BOOLEAN         DEFAULT FALSE,
  DISEASEDETAILS VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement respiratory system
 */
CREATE TABLE HEALTHSTATEMENTRESPIRATORYSYSTEM (
  ID                  BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS         BOOLEAN         DEFAULT FALSE,
  ASTHMA              BOOLEAN         DEFAULT FALSE,
  ASTHMADETAILS       VARCHAR(255),
  COPD                BOOLEAN         DEFAULT FALSE,
  COPDDETAILS         VARCHAR(255),
  OTHERDISEASE        BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement skin disorders
 */
CREATE TABLE HEALTHSTATEMENTSKINDISORDERS (
  ID                   BIGINT NOT NULL AUTO_INCREMENT,
  SKINDISORDERS        BOOLEAN         DEFAULT FALSE,
  SKINDISORDERSDETAILS VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement traumas
 */
CREATE TABLE HEALTHSTATEMENTTRAUMAS (
  ID                   BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS          BOOLEAN         DEFAULT FALSE,
  BONEFRACTURES        BOOLEAN         DEFAULT FALSE,
  BONEFRACTURESDETAILS VARCHAR(255),
  OTHERINJURIES        BOOLEAN         DEFAULT FALSE,
  OTHERINJURIESDETAILS VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement treatment up to now
 */
CREATE TABLE HEALTHSTATEMENTTREATMENTUPTONOW (
  ID                         BIGINT NOT NULL AUTO_INCREMENT,
  VISITEDDOCTORABROAD        BOOLEAN         DEFAULT FALSE,
  VISITEDDOCTORABROADDETAILS VARCHAR(255),
  REGULARLMEDICATION         BOOLEAN         DEFAULT FALSE,
  REGULARLMEDICATIONDETAILS  VARCHAR(255),
  HOSPITALIZED               BOOLEAN         DEFAULT FALSE,
  HOSPITALIZEDDETAILS        VARCHAR(255),
  SURGERY                    BOOLEAN         DEFAULT FALSE,
  SURGERYDETAILS             VARCHAR(255),
  OTHERDISEASE               BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS        VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement urogenital system
 */
CREATE TABLE HEALTHSTATEMENTUROGENITALSYSTEM (
  ID                        BIGINT NOT NULL AUTO_INCREMENT,
  NOCOMPLAINS               BOOLEAN         DEFAULT FALSE,
  KIDNEYSTONES              BOOLEAN         DEFAULT FALSE,
  KIDNEYSTONESDETAILS       VARCHAR(255),
  RENALINSUFFICIENCY        BOOLEAN         DEFAULT FALSE,
  RENALINSUFFICIENCYDETAILS VARCHAR(255),
  OTHERDISEASE              BOOLEAN         DEFAULT FALSE,
  OTHERDISEASEDETAILS       VARCHAR(255),
  PRIMARY KEY (ID) USING BTREE
)
  ENGINE = InnoDB;

/**
  Health statement
 */
CREATE TABLE HEALTHSTATEMENT (
  ID                         BIGINT NOT NULL AUTO_INCREMENT,
  PATIENT_ID                 BIGINT,
  LIFESTYLE_ID               BIGINT,
  MEDICALDEVICES_ID          BIGINT,
  CARDIOVASCULARCONDITION_ID BIGINT,
  WORKINGENVIRONMENT_ID      BIGINT,
  ALLERGIES_ID               BIGINT,
  BLOODPROBLEMS_ID           BIGINT,
  BONESJOINTSMUSCLES_ID      BIGINT,
  DIGESTIVEORGANS_ID         BIGINT,
  EARNOSETHROAT_ID           BIGINT,
  EYESANDVISION_ID           BIGINT,
  INFECTIOUSDISEASES_ID      BIGINT,
  MENTALHEALTH_ID            BIGINT,
  METABOLICDISORDERS_ID      BIGINT,
  NERVOUSSYSTEM_ID           BIGINT,
  OTHERCHRONICDISEASES_ID    BIGINT,
  RESPIRATORYSYSTEM_ID       BIGINT,
  SKINDISORDERS_ID           BIGINT,
  TRAUMAS_ID                 BIGINT,
  TREATMENTUPTONOW_ID        BIGINT,
  UROGENITALSYSTEM_ID        BIGINT,
  PRIMARY KEY (ID) USING BTREE,
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
  FOREIGN KEY (LIFESTYLE_ID) REFERENCES HEALTHSTATEMENTLIFESTYLE (ID),
  FOREIGN KEY (MEDICALDEVICES_ID) REFERENCES HEALTHSTATEMENTMEDICALDEVICES (ID),
  FOREIGN KEY (CARDIOVASCULARCONDITION_ID) REFERENCES HEALTHSTATEMENTCARDIOVASCULARCONDITION (ID),
  FOREIGN KEY (WORKINGENVIRONMENT_ID) REFERENCES HEALTHSTATEMENTWORKINGENVIRONMENT (ID),
  FOREIGN KEY (ALLERGIES_ID) REFERENCES HEALTHSTATEMENTALLERGIES (ID),
  FOREIGN KEY (BLOODPROBLEMS_ID) REFERENCES HEALTHSTATEMENTBLOODPROBLEMS (ID),
  FOREIGN KEY (BONESJOINTSMUSCLES_ID) REFERENCES HEALTHSTATEMENTBONESJOINTSMUSCLES (ID),
  FOREIGN KEY (DIGESTIVEORGANS_ID) REFERENCES HEALTHSTATEMENTDIGESTIVEORGANS (ID),
  FOREIGN KEY (EARNOSETHROAT_ID) REFERENCES HEALTHSTATEMENTEARNOSETHROAT (ID),
  FOREIGN KEY (EYESANDVISION_ID) REFERENCES HEALTHSTATEMENTEYESANDVISION (ID),
  FOREIGN KEY (INFECTIOUSDISEASES_ID) REFERENCES HEALTHSTATEMENTINFECTIOUSDISEASES (ID),
  FOREIGN KEY (MENTALHEALTH_ID) REFERENCES HEALTHSTATEMENTMENTALHEALTH (ID),
  FOREIGN KEY (METABOLICDISORDERS_ID) REFERENCES HEALTHSTATEMENTMETABOLICDISORDERS (ID),
  FOREIGN KEY (NERVOUSSYSTEM_ID) REFERENCES HEALTHSTATEMENTNERVOUSSYSTEM (ID),
  FOREIGN KEY (OTHERCHRONICDISEASES_ID) REFERENCES HEALTHSTATEMENTOTHERCHRONICDISEASES (ID),
  FOREIGN KEY (RESPIRATORYSYSTEM_ID) REFERENCES HEALTHSTATEMENTRESPIRATORYSYSTEM (ID),
  FOREIGN KEY (SKINDISORDERS_ID) REFERENCES HEALTHSTATEMENTSKINDISORDERS (ID),
  FOREIGN KEY (TRAUMAS_ID) REFERENCES HEALTHSTATEMENTTRAUMAS (ID),
  FOREIGN KEY (TREATMENTUPTONOW_ID) REFERENCES HEALTHSTATEMENTTREATMENTUPTONOW (ID),
  FOREIGN KEY (UROGENITALSYSTEM_ID) REFERENCES HEALTHSTATEMENTUROGENITALSYSTEM (ID)
)
  ENGINE =InnoDB;

