/**
  Self health check
 */
CREATE TABLE SELFHEALTHCHECK (
  ID                       BIGINT NOT NULL AUTO_INCREMENT,
  PATIENT_ID               BIGINT,
  HEADACHE                 BOOLEAN         DEFAULT FALSE,
  PAININBONES              BOOLEAN         DEFAULT FALSE,
  PAININRESPIRATORYTRACT   BOOLEAN         DEFAULT FALSE,
  STOMACHACHETOP           BOOLEAN         DEFAULT FALSE,
  STOMACHACHEMIDDLE        BOOLEAN         DEFAULT FALSE,
  STOMACHACHEBOTTOM        BOOLEAN         DEFAULT FALSE,
  RHEUM                    BOOLEAN         DEFAULT FALSE,
  COUGH                    BOOLEAN         DEFAULT FALSE,
  PAININTHROAT             BOOLEAN         DEFAULT FALSE,
  PAININLUNGS              BOOLEAN         DEFAULT FALSE,
  RHEUMANDTHROAT           BOOLEAN         DEFAULT FALSE,
  STITCHESINHEARTZONE      BOOLEAN         DEFAULT FALSE,
  STITCHESINOTHERBODYPARTS BOOLEAN         DEFAULT FALSE,
  CARDIACRHYTHMDISORDERS   BOOLEAN         DEFAULT FALSE,
  FEVER                    BOOLEAN         DEFAULT FALSE,
  VOMITING                 BOOLEAN         DEFAULT FALSE,
  DIARRHEA                 BOOLEAN         DEFAULT FALSE,
  INJURY                   BOOLEAN         DEFAULT FALSE,
  INFLAMMATIONVISIBLE      BOOLEAN         DEFAULT FALSE,
  INFLAMMATIONNOTVISIBLE   BOOLEAN         DEFAULT FALSE,
  URINATION                BOOLEAN         DEFAULT FALSE,
  ANXIETY                  BOOLEAN         DEFAULT FALSE,

  PRIMARY KEY (ID) USING BTREE,
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID)
)
  ENGINE = InnoDB;

ALTER TABLE SELFHEALTHCHECK ADD INDEX patient_id (PATIENT_ID);